# -*- coding: utf-8 -*-
"""psychology test-Bar-On

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OHr7S6Na86tthxvY0Ei5ceddU25tOTxQ

Create a Python file

The first step towards building the test app is to create a python file, we can call it personality.py.

Import the python module sys In this module, we would use the exit() function to terminate the first interactive option we want to give our users.
"""

import sys

"""A function that displays the personality identity

We will use the function declared here to display our user’s personality identity after the test.
"""

def display():
    print(f":نتیجه تست بار آن شما اینست \n", "حل مسئله = ", Ps , "\n شادمانی = ",Ha ,"\n استقلال = ",IIN , "\n تحمل فشار روانی = ",st ,
          "\n خودشکوفایی = ",rt , "\n  خودآگاهی هیجانی = ",es ,"\n واقع‌گرایی = ",ir , "\n روابط بین فردی = ",op ,"\n خوش‌بینی = ",sr , "\n احترام به خود = ",ic ,
          "\n خویشتن‌داری یا کنترل تکانش = ",sa , "\n انعطاف پذیری = ",fl ,"\n مسئولیت‌پذیری (اجتماعی) = ",re , "\n همدلی = ",em ,  "\n خودابرازی = ",ass )

"""A function that computes the personality test

This function will implement all our logic. So we have to store our test questions into a list.
"""

def run():
    questions: list = [
        """
 به نظر من برای غلبه بر مشکلات باید گام به گام پیش رفت
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
لذت بردن از زندگی برام مشکل است
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
 شغلی را ترجیح می‌دهم که حتی الامکان من تصمیم گیرنده باشم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
می‌توانم بدون تنش زیاد با مشکلات مقابله کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
می‌توانم برای معنی دادن به زندگی تا حد زیادی تلاش کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
نسبت به هیجاناتم آگاهم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
سعی می‌کنم بدون خیال‌پردازی، واقعیت امور را در نظر بگیرم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
به راحتی با دیگران دوست می‌شوم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
معتقدم توانایی تسلط بر شرایط دشوار را دارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
بیشتر مواقع به خودم اطمینان دارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
کنترل خشم برایم مشکل است
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
شروع دوباره برایم سخت است
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
کمک به دیگران را دوست دارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
به خوبی می‌توانم احساسات دیگران را درک کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
هنگامی که از دیگران خشمگین می‌شوم نمی‌توانم با آنها در این مورد صحبت کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
هنگام رویارویی با یک موقعیت دشوار، دوست دارم تا حد ممکن درباره آن اطلاعات جمع کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
خندیدن برایم سخت است
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
هنگام کار کردن با دیگران بیشتر پیرو افکار آنها هستم تا فکر خودم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
نمی‌توانم به خوبی فشارها را تحمل کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
""",
        """
در چند سال گذشته کمترین کار را به نتیجه رسانده‌ام
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به سختی می‌توانم احساسات عمیقم را با دیگران در میان بگذارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
دیگران نمی‌فهمند که من چه فکری دارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به خوبی با دیگران همراهی می‌کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به اغلب کارهایی که انجام می‌دهم خوش‌بین هستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
برای خودم احترام قائل هستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
عصبی بودنم مشکل ایجاد می‌کند
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به سختی می‌توانم فکرم را در مورد مسائل تغییر دهم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
کمک به دیگران من را کسل نمی‌کند، بخصوص اگر شایستگی آن را داشته باشند
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
دوستانم می‌توانند مسائل خصوصی خودشان را با من درمیان بگذارند
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
می‌توانم مخالفتم را به دیگران ابراز نمایم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
هنگام مواجهه با یک مشکل، اولین کاری که انجام می‌دهم دست نگهداشتن و فکر کردن است
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
فرد با نشاطی هستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
ترجیح می‌دهم دیگران برایم تصمیم بگیرند
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
احساس می‌کنم کنترل اضطراب برایم مشکل است
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
از کارهایی که انجام می‌دهم راضی نیستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به سختی میفهمم چه احساسی دارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
تمایل دارم با آن‌چه در اطرافم می‌گذرد روبه‌رو نشوم و از برخورد با آن‌ها طفره میروم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
روابط صمیمی با دوستانم برای هر دو طرفمان اهمیت دارد
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
حتی در موقعیت‌های دشوار، معمولاً برای ادامه کار انگیزه دارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
نمیتوانم خودم را این‌طور که هستم بپذیرم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
دیگران به من میگویند هنگام بحث، آرام‌تر صحبت کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به آسانی با شرایط جدید سازگار میشوم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به کودک گمشده کمک میکنم، حتی اگر همان موقع جای دیگری کار داشته باشم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به اتفاقی که برای دیگران می‌افتد توجه دارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
نه گفتن برایم مشکل است
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
هنگام تلاش برای حل یک مشکل، راه حل‌های ممکن را در نظر می‌آورم. سپس بهترین را انتخاب می‌کنم.
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
از زندگی‌ام راضی هستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
تصمیم‌گیری برایم مشکل است
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
میدانم در شرایط دشوار، چگونه آرامشم را حفظ کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
هیچ‌چیز در من علاقه ایجاد نمی‌کند
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
از احساسی که دارم آگاهم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
در تصورات و خیال‌پردازی‌هایم غرق می‌شوم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
با دیگران رابطه خوبی دارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
معمولاً انتظار دارم مشکلات به خوبی ختم شوند. هر چند چنین نمی‌شود
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
از اندام و ظاهر خودم راضی هستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
کم صبر هستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
می‌توانم عادات قبلی‌ام را تغییر دهم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
اگر لازم باشد با زیر پا گذاشتن قانون از موقعیتی فرار کنم، این کار را انجام می‌دهم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
نسبت به احساسات دیگران حساس هستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
می‌توانم به راحتی افکارم را به دیگران بگویم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
هنگام حل مسائل، به سختی می‌توانم در مورد بهترین انتخاب تصمیم گیری کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
اهل شوخی هستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
در انجام کارها و امور مختلف به دیگران وابسته‌ام
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
رویارویی با مسائل ناخوشایند برایم مشکل است
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
حتی‌الامکان کارهایی را به عهده می‌گیرم که برایم لذت بخش هستند
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
حتی هنگام آشفتگی، از آن‌چه در من اتفاق می‌افتد آگاهم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
تمایل به مبالغه‌گویی دارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به نظر دیگران من فردی اجتماعی هستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به توانایی‌ام برای مقابله با دشوارترین مسائل اطمینان دارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
از شیوه نگرش و فکرم راضی هستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به طرز بدی خشمگین می‌شوم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
معمولاً تغییر ایجاد کردن در زندگی روزانه برایم سخت است
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
قادر هستم احترام به دیگران را حفظ کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
دیدن رنج دیگران برایم سخت است
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به نظر دیگران من نمی‌توانم احساسات و افکارم را بروز دهم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
هنگام روبه‌رو شدن با شرایط دشوار، سعی می‌کنم درمورد راه‌حل‌های ممکن فکر کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
افسرده هستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
فکر میکنم به دیگران بیشتر احتیاج دارم، تا دیگران به من
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
مضطرب هستم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
درمورد آنچه می‌خواهم در زندگی انجام دهم فکر مشخص و خوبی ندارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به سختی می‌توانم از امور برداشت صحیحی داشته باشم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به سختی می‌توانم احساساتم را بیان کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
با دوستانم رابطه صمیمی برقرار می‌کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
قبل از شروع کارهای جدید، معمولاً احساس می‌کنم شکست خواهم خورد
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
هنگام بررسی نقاط ضعف و قوتم، باز هم احساس خوبی در مورد خودم دارم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
هنگام عصبانیت زود از کوره در میروم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
اگر مجبور به ترک وطنم باشم، سازگاری برایم دشوار خواهد بود
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
به نظر من پایبندی یک شهروند به قانون مهم است
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
از جریجه دار کردن احساسات دیگران خودداری می‌کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""
,
        """
مشکل می‌توانم از حق خودم دفاع کنم
a. کاملا مخالفم
b. مخالفم
c. تا حدودی
d. موافقم
e. کاملا موافقم
"""

    ]
    questions2: list=[questions[1],questions[10],questions[11],questions[14],questions[16],
                     questions[17],questions[18],questions[19],questions[20],questions[21],
                     questions[25],questions[26],questions[32],questions[33],questions[34],
                     questions[35],questions[36],questions[39],questions[40],questions[44],
                     questions[47],questions[49],questions[51],questions[55],questions[57],
                     questions[60],questions[62],questions[63],questions[66],questions[70],questions[71]]


    Ps: int = 0
    Ha: int = 0
    IIN: int = 0
    st: int = 0
    rt: int = 0
    es: int = 0
    ir: int = 0
    op: int = 0
    sr: int = 0
    ic: int = 0
    sa: int = 0
    fl: int = 0
    re: int = 0
    em: int = 0
    ass: int = 0
    meghdar=0

    Ps1= [questions[0], questions[15],questions[30],questions[45],questions[60],questions[76]]
    Ha1= [questions[1],questions[16],questions[31],questions[46],questions[61],questions[76]]
    IIN1=[questions[2], questions[17],questions[32],questions[47],questions[62],questions[77]]
    st1= [questions[3],questions[18],questions[33],questions[48],questions[63],questions[78]]
    rt1= [questions[4],questions[19],questions[34],questions[49],questions[64],questions[79]]
    es1= [questions[5],questions[20],questions[35],questions[50],questions[65],questions[80]]
    ir1= [questions[6],questions[21],questions[36],questions[51],questions[66],questions[81]]
    op1= [questions[7],questions[22],questions[37],questions[52],questions[67],questions[82]]
    sr1= [questions[8],questions[23],questions[38],questions[53],questions[68],questions[83]]
    ic1= [questions[9],questions[24],questions[39],questions[54],questions[69],questions[84]]
    sa1= [questions[10],questions[25],questions[40],questions[55],questions[70],questions[85]]
    fl1= [questions[11],questions[26],questions[41],questions[56],questions[71],questions[86]]
    re1= [questions[12],questions[27],questions[42],questions[57],questions[72],questions[87]]
    em1= [questions[13],questions[28],questions[43],questions[58],questions[73],questions[88]]
    ass1= [questions[14] ,questions[29],questions[44],questions[59],questions[74],questions[89]]

    for question in questions:
        answer = ''
        while not (answer == 'A' or answer == 'B' or answer == 'C' or answer == 'D' or answer == 'E'):
            question==0
            try:
                answer = input(question).upper()
                if not (answer == 'A' or answer == 'B' or answer == 'C' or answer == 'D' or answer == 'E'):
                    raise ValueError("Invalid input")
            except ValueError as error:
                print(error)

            else:
                  if question in questions2:
                    if answer == 'A':                     
                      if question in  Ps1:
                        Ps=Ps+ 5  
                      elif question in  Ha1:
                        Ha=Ha+ 5  
                      elif question in  IIN1:
                        IIN=IIN+ 5                                          
                      elif question in  st1:
                        st=st+ 5  
                      elif question in  rt1:
                        rt=rt+ 5  
                      elif question in  es1:
                        es=es+ 5  
                      elif question in  ir1:
                        ir=ir+ 5  
                      elif question in  op1:
                        op=op+5  
                      elif question in  sr1:
                        sr=sr+5  
                      elif question in  ic1:
                        ic=ic+ 5  
                      elif question in  sa1:
                        sa=sa+ 5                      
                      elif question in  fl1:
                        fl=fl+ 5  
                      elif question in  re1:
                        re=re+ 5  
                      elif question in  em1:
                        em=em+ 5  
                      elif question in  ass1:
                        ass=ass+5  


                    if answer == 'B':

                      if question in  Ps1:
                        Ps=Ps+ 4  
                      elif question in  Ha1:
                        Ha=Ha+ 4  
                      elif question in  IIN1:
                        IIN=IIN+ 4                                          
                      elif question in  st1:
                        st=st+ 4  
                      elif question in  rt1:
                        rt=rt+ 4  
                      elif question in  es1:
                        es=es+ 4 
                      elif question in  ir1:
                        ir=ir+ 4  
                      elif question in  op1:
                        op=op+4  
                      elif question in  sr1:
                        sr=sr+4  
                      elif question in  ic1:
                        ic=ic+ 4  
                      elif question in  sa1:
                        sa=sa+4                      
                      elif question in  fl1:
                        fl=fl+ 4  
                      elif question in  re1:
                        re=re+4  
                      elif question in  em1:
                        em=em+4  
                      elif question in  ass1:
                        ass=ass+4  


                    if answer == 'C':
                      if question in  Ps1:
                        Ps=Ps+3 
                      elif question in  Ha1:
                        Ha=Ha+3  
                      elif question in  IIN1:
                        IIN=IIN+3                                         
                      elif question in  st1:
                        st=st+3  
                      elif question in  rt1:
                        rt=rt+3  
                      elif question in  es1:
                        es=es+3 
                      elif question in  ir1:
                        ir=ir+3 
                      elif question in  op1:
                        op=op+3  
                      elif question in  sr1:
                        sr=sr+3 
                      elif question in  ic1:
                        ic=ic+3 
                      elif question in  sa1:
                        sa=sa+3                     
                      elif question in  fl1:
                        fl=fl+3 
                      elif question in  re1:
                        re=re+3  
                      elif question in  em1:
                        em=em+3  
                      elif question in  ass1:
                        ass=ass+3  



                    if answer == 'D':
                      if question in  Ps1:
                        Ps=Ps+2 
                      elif question in  Ha1:
                        Ha=Ha+2  
                      elif question in  IIN1:
                        IIN=IIN+2                                         
                      elif question in  st1:
                        st=st+2  
                      elif question in  rt1:
                        rt=rt+2  
                      elif question in  es1:
                        es=es+2 
                      elif question in  ir1:
                        ir=ir+2 
                      elif question in  op1:
                        op=op+2  
                      elif question in  sr1:
                        sr=sr+2 
                      elif question in  ic1:
                        ic=ic+2 
                      elif question in  sa1:
                        sa=sa+2                     
                      elif question in  fl1:
                        fl=fl+2 
                      elif question in  re1:
                        re=re+2  
                      elif question in  em1:
                        em=em+2  
                      elif question in  ass1:
                        ass=ass+2                       
 

                    if answer == 'E':
                      if question in  Ps1:
                        Ps=Ps+1 
                      elif question in  Ha1:
                        Ha=Ha+1  
                      elif question in  IIN1:
                        IIN=IIN+1                                         
                      elif question in  st1:
                        st=st+1  
                      elif question in  rt1:
                        rt=rt+1  
                      elif question in  es1:
                        es=es+1 
                      elif question in  ir1:
                        ir=ir+1 
                      elif question in  op1:
                        op=op+1  
                      elif question in  sr1:
                        sr=sr+1 
                      elif question in  ic1:
                        ic=ic+1 
                      elif question in  sa1:
                        sa=sa+1                     
                      elif question in  fl1:
                        fl=fl+1 
                      elif question in  re1:
                        re=re+1  
                      elif question in  em1:
                        em=em+1  
                      elif question in  ass1:
                        ass=ass+1 



                  else:
                   if answer == 'A':
                     if question in  Ps1:
                       Ps=Ps+1 
                     elif question in  Ha1:
                       Ha=Ha+1  
                     elif question in  IIN1:
                       IIN=IIN+1                                         
                     elif question in  st1:
                       st=st+1  
                     elif question in  rt1:
                       rt=rt+1  
                     elif question in  es1:
                       es=es+1 
                     elif question in  ir1:
                       ir=ir+1 
                     elif question in  op1:
                       op=op+1  
                     elif question in  sr1:
                       sr=sr+1 
                     elif question in  ic1:
                       ic=ic+1 
                     elif question in  sa1:
                       sa=sa+1                     
                     elif question in  fl1:
                       fl=fl+1 
                     elif question in  re1:
                       re=re+1  
                     elif question in  em1:
                       em=em+1  
                     elif question in  ass1:
                       ass=ass+1 



                   if answer == 'B':
                     if question in  Ps1:
                       Ps=Ps+2 
                     elif question in  Ha1:
                       Ha=Ha+2  
                     elif question in  IIN1:
                       IIN=IIN+2                                         
                     elif question in  st1:
                       st=st+2  
                     elif question in  rt1:
                       rt=rt+2  
                     elif question in  es1:
                       es=es+2 
                     elif question in  ir1:
                       ir=ir+2 
                     elif question in  op1:
                       op=op+2  
                     elif question in  sr1:
                       sr=sr+2 
                     elif question in  ic1:
                       ic=ic+2 
                     elif question in  sa1:
                       sa=sa+2                     
                     elif question in  fl1:
                       fl=fl+2 
                     elif question in  re1:
                       re=re+2  
                     elif question in  em1:
                       em=em+2  
                     elif question in  ass1:
                      ass=ass+2 


                   if answer == 'C':
                     if question in  Ps1:
                       Ps=Ps+3 
                     elif question in  Ha1:
                       Ha=Ha+3  
                     elif question in  IIN1:
                       IIN=IIN+3                                         
                     elif question in  st1:
                       st=st+3  
                     elif question in  rt1:
                       rt=rt+3  
                     elif question in  es1:
                       es=es+3 
                     elif question in  ir1:
                       ir=ir+3 
                     elif question in  op1:
                       op=op+3  
                     elif question in  sr1:
                       sr=sr+3 
                     elif question in  ic1:
                       ic=ic+3 
                     elif question in  sa1:
                       sa=sa+3                     
                     elif question in  fl1:
                       fl=fl+3 
                     elif question in  re1:
                       re=re+3  
                     elif question in  em1:
                       em=em+3  
                     elif question in  ass1:
                       ass=ass+3 


                   if answer == 'D':
                     if question in  Ps1:
                       Ps=Ps+4 
                     elif question in  Ha1:
                       Ha=Ha+4 
                     elif question in  IIN1:
                       IIN=IIN+4                                         
                     elif question in  st1:
                       st=st+4  
                     elif question in  rt1:
                       rt=rt+4  
                     elif question in  es1:
                       es=es+4 
                     elif question in  ir1:
                       ir=ir+4 
                     elif question in  op1:
                       op=op+4  
                     elif question in  sr1:
                       sr=sr+4 
                     elif question in  ic1:
                       ic=ic+4 
                     elif question in  sa1:
                       sa=sa+4                     
                     elif question in  fl1:
                       fl=fl+4 
                     elif question in  re1:
                       re=re+4  
                     elif question in  em1:
                       em=em+4  
                     elif question in  ass1:
                       ass=ass+4 

                      

                   if answer == 'E':                                        
                     if question in  Ps1:
                       Ps=Ps+5 
                     elif question in  Ha1:
                       Ha=Ha+5  
                     elif question in  IIN1:
                       IIN=IIN+5                                         
                     elif question in  st1:
                       st=st+5  
                     elif question in  rt1:
                       rt=rt+5  
                     elif question in  es1:
                       es=es+5 
                     elif question in  ir1:
                       ir=ir+5 
                     elif question in  op1:
                       op=op+5  
                     elif question in  sr1:
                       sr=sr+5 
                     elif question in  ic1:
                       ic=ic+5 
                     elif question in  sa1:
                       sa=sa+5                     
                     elif question in  fl1:
                       fl=fl+5 
                     elif question in  re1:
                       re=re+5  
                     elif question in  em1:
                       em=em+5  
                     elif question in  ass1:
                       ass=ass+5 


    display()

"""# ***The overview of the functions***
**The run function**

In the run function, we set variables to keep track of users’ options, which helps us compute the personality identities as they enter them. The variables are meant to count the occurrence of A’s,B’s,C's,D's,E's and E's as answers, and then use that to compute the identity accordingly.
"""

Ps: int = 0
Ha: int = 0
IIN: int = 0
st: int = 0
rt: int = 0
es: int = 0
ir: int = 0
op: int = 0
sr: int = 0
ic: int = 0
sa: int = 0
fl: int = 0
re: int = 0
em: int = 0
ass: int = 0
personality_dichotomy: str = ''

"""We then set counters to zero. The code snippet below is meant to keep the counters unchanged when wrong input is entered."""

for question in questions:
        answer = ''
        while not (answer == 'A' or answer == 'B' or answer == 'C' or answer == 'D' or answer == 'E'):
            question==0

"""Exception handling

The code snippet below handles the problem of incorrect input from the user. We only want the user to enter A , B,C,D or E. If our expected letter is entered, we count its occurrence.
"""

try:
                answer = input(question).upper()
                if not (answer == 'A' or answer == 'B' or answer == 'C' or answer == 'D' or answer == 'E'):
                    raise ValueError("Invalid input")
            except ValueError as error:
                print(error)

"""We then compute the identities with if statements.

We use our variable counters and if statements to compute the personality identity. The count keeps track of the questions ranging from 1 to 90 and a total of four sections.
"""

else:
                  if question in questions2:
                    if answer == 'A':                     
                      if question in  Ps1:
                        Ps=Ps+ 5  
                      elif question in  Ha1:
                        Ha=Ha+ 5  
                      elif question in  IIN1:
                        IIN=IIN+ 5                                          
                      elif question in  st1:
                        st=st+ 5  
                      elif question in  rt1:
                        rt=rt+ 5  
                      elif question in  es1:
                        es=es+ 5  
                      elif question in  ir1:
                        ir=ir+ 5  
                      elif question in  op1:
                        op=op+5  
                      elif question in  sr1:
                        sr=sr+5  
                      elif question in  ic1:
                        ic=ic+ 5  
                      elif question in  sa1:
                        sa=sa+ 5                      
                      elif question in  fl1:
                        fl=fl+ 5  
                      elif question in  re1:
                        re=re+ 5  
                      elif question in  em1:
                        em=em+ 5  
                      elif question in  ass1:
                        ass=ass+5  


                    if answer == 'B':

                      if question in  Ps1:
                        Ps=Ps+ 4  
                      elif question in  Ha1:
                        Ha=Ha+ 4  
                      elif question in  IIN1:
                        IIN=IIN+ 4                                          
                      elif question in  st1:
                        st=st+ 4  
                      elif question in  rt1:
                        rt=rt+ 4  
                      elif question in  es1:
                        es=es+ 4 
                      elif question in  ir1:
                        ir=ir+ 4  
                      elif question in  op1:
                        op=op+4  
                      elif question in  sr1:
                        sr=sr+4  
                      elif question in  ic1:
                        ic=ic+ 4  
                      elif question in  sa1:
                        sa=sa+4                      
                      elif question in  fl1:
                        fl=fl+ 4  
                      elif question in  re1:
                        re=re+4  
                      elif question in  em1:
                        em=em+4  
                      elif question in  ass1:
                        ass=ass+4  


                    if answer == 'C':
                      if question in  Ps1:
                        Ps=Ps+3 
                      elif question in  Ha1:
                        Ha=Ha+3  
                      elif question in  IIN1:
                        IIN=IIN+3                                         
                      elif question in  st1:
                        st=st+3  
                      elif question in  rt1:
                        rt=rt+3  
                      elif question in  es1:
                        es=es+3 
                      elif question in  ir1:
                        ir=ir+3 
                      elif question in  op1:
                        op=op+3  
                      elif question in  sr1:
                        sr=sr+3 
                      elif question in  ic1:
                        ic=ic+3 
                      elif question in  sa1:
                        sa=sa+3                     
                      elif question in  fl1:
                        fl=fl+3 
                      elif question in  re1:
                        re=re+3  
                      elif question in  em1:
                        em=em+3  
                      elif question in  ass1:
                        ass=ass+3  



                    if answer == 'D':
                      if question in  Ps1:
                        Ps=Ps+2 
                      elif question in  Ha1:
                        Ha=Ha+2  
                      elif question in  IIN1:
                        IIN=IIN+2                                         
                      elif question in  st1:
                        st=st+2  
                      elif question in  rt1:
                        rt=rt+2  
                      elif question in  es1:
                        es=es+2 
                      elif question in  ir1:
                        ir=ir+2 
                      elif question in  op1:
                        op=op+2  
                      elif question in  sr1:
                        sr=sr+2 
                      elif question in  ic1:
                        ic=ic+2 
                      elif question in  sa1:
                        sa=sa+2                     
                      elif question in  fl1:
                        fl=fl+2 
                      elif question in  re1:
                        re=re+2  
                      elif question in  em1:
                        em=em+2  
                      elif question in  ass1:
                        ass=ass+2                       
 

                    if answer == 'E':
                      if question in  Ps1:
                        Ps=Ps+1 
                      elif question in  Ha1:
                        Ha=Ha+1  
                      elif question in  IIN1:
                        IIN=IIN+1                                         
                      elif question in  st1:
                        st=st+1  
                      elif question in  rt1:
                        rt=rt+1  
                      elif question in  es1:
                        es=es+1 
                      elif question in  ir1:
                        ir=ir+1 
                      elif question in  op1:
                        op=op+1  
                      elif question in  sr1:
                        sr=sr+1 
                      elif question in  ic1:
                        ic=ic+1 
                      elif question in  sa1:
                        sa=sa+1                     
                      elif question in  fl1:
                        fl=fl+1 
                      elif question in  re1:
                        re=re+1  
                      elif question in  em1:
                        em=em+1  
                      elif question in  ass1:
                        ass=ass+1 



                  else:
                   if answer == 'A':
                     if question in  Ps1:
                       Ps=Ps+1 
                     elif question in  Ha1:
                       Ha=Ha+1  
                     elif question in  IIN1:
                       IIN=IIN+1                                         
                     elif question in  st1:
                       st=st+1  
                     elif question in  rt1:
                       rt=rt+1  
                     elif question in  es1:
                       es=es+1 
                     elif question in  ir1:
                       ir=ir+1 
                     elif question in  op1:
                       op=op+1  
                     elif question in  sr1:
                       sr=sr+1 
                     elif question in  ic1:
                       ic=ic+1 
                     elif question in  sa1:
                       sa=sa+1                     
                     elif question in  fl1:
                       fl=fl+1 
                     elif question in  re1:
                       re=re+1  
                     elif question in  em1:
                       em=em+1  
                     elif question in  ass1:
                       ass=ass+1 



                   if answer == 'B':
                     if question in  Ps1:
                       Ps=Ps+2 
                     elif question in  Ha1:
                       Ha=Ha+2  
                     elif question in  IIN1:
                       IIN=IIN+2                                         
                     elif question in  st1:
                       st=st+2  
                     elif question in  rt1:
                       rt=rt+2  
                     elif question in  es1:
                       es=es+2 
                     elif question in  ir1:
                       ir=ir+2 
                     elif question in  op1:
                       op=op+2  
                     elif question in  sr1:
                       sr=sr+2 
                     elif question in  ic1:
                       ic=ic+2 
                     elif question in  sa1:
                       sa=sa+2                     
                     elif question in  fl1:
                       fl=fl+2 
                     elif question in  re1:
                       re=re+2  
                     elif question in  em1:
                       em=em+2  
                     elif question in  ass1:
                      ass=ass+2 


                   if answer == 'C':
                     if question in  Ps1:
                       Ps=Ps+3 
                     elif question in  Ha1:
                       Ha=Ha+3  
                     elif question in  IIN1:
                       IIN=IIN+3                                         
                     elif question in  st1:
                       st=st+3  
                     elif question in  rt1:
                       rt=rt+3  
                     elif question in  es1:
                       es=es+3 
                     elif question in  ir1:
                       ir=ir+3 
                     elif question in  op1:
                       op=op+3  
                     elif question in  sr1:
                       sr=sr+3 
                     elif question in  ic1:
                       ic=ic+3 
                     elif question in  sa1:
                       sa=sa+3                     
                     elif question in  fl1:
                       fl=fl+3 
                     elif question in  re1:
                       re=re+3  
                     elif question in  em1:
                       em=em+3  
                     elif question in  ass1:
                       ass=ass+3 


                   if answer == 'D':
                     if question in  Ps1:
                       Ps=Ps+4 
                     elif question in  Ha1:
                       Ha=Ha+4 
                     elif question in  IIN1:
                       IIN=IIN+4                                         
                     elif question in  st1:
                       st=st+4  
                     elif question in  rt1:
                       rt=rt+4  
                     elif question in  es1:
                       es=es+4 
                     elif question in  ir1:
                       ir=ir+4 
                     elif question in  op1:
                       op=op+4  
                     elif question in  sr1:
                       sr=sr+4 
                     elif question in  ic1:
                       ic=ic+4 
                     elif question in  sa1:
                       sa=sa+4                     
                     elif question in  fl1:
                       fl=fl+4 
                     elif question in  re1:
                       re=re+4  
                     elif question in  em1:
                       em=em+4  
                     elif question in  ass1:
                       ass=ass+4 

                      

                   if answer == 'E':                                        
                     if question in  Ps1:
                       Ps=Ps+5 
                     elif question in  Ha1:
                       Ha=Ha+5  
                     elif question in  IIN1:
                       IIN=IIN+5                                         
                     elif question in  st1:
                       st=st+5  
                     elif question in  rt1:
                       rt=rt+5  
                     elif question in  es1:
                       es=es+5 
                     elif question in  ir1:
                       ir=ir+5 
                     elif question in  op1:
                       op=op+5  
                     elif question in  sr1:
                       sr=sr+5 
                     elif question in  ic1:
                       ic=ic+5 
                     elif question in  sa1:
                       sa=sa+5                     
                     elif question in  fl1:
                       fl=fl+5 
                     elif question in  re1:
                       re=re+5  
                     elif question in  em1:
                       em=em+5  
                     elif question in  ass1:
                       ass=ass+5

"""Quit the app with exit function This is a separate function that allows the user to exit the application. The sys module here enables us to exit from the terminal if the user decides not to take the test."""

def exit_application():
    print("Exiting application...")
    sys.exit(0)

"""Homepage function

This function is designed to mimic a landing page on the web. We only accept two options (1 or 2). We also checked for wrong inputs using python exception handling.
"""

def main():
       user_input = input("""
       Welcome to the Meyers Briggs Personality Test
       Press 1  to take test
       Press 2 to exit application -> """)
       try:
              if not (user_input == "1" or user_input == "2"):
                     raise ValueError("Invalid input")
       except ValueError as error:
              print(error)
       else:
              switcher = {
                     "1": run,
                     "2": exit_application
       }
       return switcher.get(user_input)()

if __name__ == "__main__":
   main()